### ISSUE TITLE
Panic error on OVH VPS

### ISSUE THREAD

**Issue by guiguiabloc** [ovh/svfs#126]
### Context
- svfs version : 0.9.1
- storage provider : ovh
- product : hubic

### Steps to reproduce this issue :

1. mount hubic on VPS OVH SSD Linux Debian 7.11 AMD64
2. mount -t svfs -o uid=0,gid=0,token=1234,storage_url=https://lb1.hubic.ovh.net/v1/AUTH_1234,container=default hubic /data
3.

### Results you expected :

mount 
### Results you observed :

panic
### Debug log :

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5890ab]

goroutine 1 [running]:
panic(0x8ab5a0, 0xc420010080)
	/home/xlucas/.gvm/gos/go1.7/src/runtime/panic.go:500 +0x1a1
github.com/ovh/svfs/svfs.(*swiftACLAuth).Request(0xc4200a99a0, 0xc420072a00, 0xc42016b578, 0x429353, 0xc42016b548)
	<autogenerated>:4 +0x3b
github.com/ovh/svfs/vendor/github.com/xlucas/swift.(*Connection).authenticate(0xc420072a00, 0x0, 0x0)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/vendor/github.com/xlucas/swift/swift.go:307 +0x15e
github.com/ovh/svfs/vendor/github.com/xlucas/swift.(*Connection).getUrlAndAuthToken(0xc420072a00, 0xc420018fa0, 0x42, 0xc420109080, 0xc420018fa0, 0x42, 0x0, 0x0, 0x0, 0x0)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/vendor/github.com/xlucas/swift/swift.go:356 +0x129
github.com/ovh/svfs/vendor/github.com/xlucas/swift.(*Connection).Call(0xc420072a00, 0xc420018fa0, 0x42, 0x7ffe22e76946, 0x7, 0x0, 0x0, 0x938372, 0x4, 0x0, ...)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/vendor/github.com/xlucas/swift/swift.go:470 +0x159
github.com/ovh/svfs/vendor/github.com/xlucas/swift.(*Connection).storage(0xc420072a00, 0x7ffe22e76946, 0x7, 0x0, 0x0, 0x938372, 0x4, 0x0, 0x0, 0xc42000fad0, ...)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/vendor/github.com/xlucas/swift/swift.go:576 +0x118
github.com/ovh/svfs/vendor/github.com/xlucas/swift.(*Connection).Container(0xc420072a00, 0x7ffe22e76946, 0x7, 0x40badf, 0xbb8e68, 0x101, 0xbbaec0, 0x7f24f41293f8, 0x100000000000000, 0x1051e53aa7a)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/vendor/github.com/xlucas/swift/swift.go:1064 +0xd7
github.com/ovh/svfs/svfs.(*SVFS).rootContainer(0xbb8c40, 0x7ffe22e76946, 0x7, 0x40d359, 0x8b3960, 0x8c8620, 0xc42011ba01)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/svfs/fs.go:174 +0x76
github.com/ovh/svfs/svfs.(*SVFS).Root(0xbb8c40, 0xb73e00, 0xbb8c40, 0xc42011bb78, 0xb9d400)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/svfs/fs.go:113 +0x53
github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).Serve(0xc4200ec0c0, 0xb73e00, 0xbb8c40, 0x0, 0x0)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:399 +0x1a6
github.com/ovh/svfs/cmd.glob..func1(0xb95fe0, 0xc42006c510, 0x0, 0x9)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/cmd/mount.go:129 +0x40a
github.com/ovh/svfs/vendor/github.com/spf13/cobra.(*Command).execute(0xb95fe0, 0xc42006c3f0, 0x9, 0x9, 0xb95fe0, 0xc42006c3f0)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/vendor/github.com/spf13/cobra/command.go:603 +0x439
github.com/ovh/svfs/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb96200, 0xb96200, 0xc42003bf20, 0x0)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/ovh/svfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xb96200, 0x1, 0x1)
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/home/xlucas/.gvm/pkgsets/go1.7/global/src/github.com/ovh/svfs/main.go:9 +0x31
```

**Comment by xlucas** [comment]
Use [hubic options](https://github.com/ovh/svfs#hubic-options) instead.
