### ISSUE TITLE
Unable to backup on swift storage from Proxmox

### ISSUE THREAD

**Issue by ele0s** [ovh/svfs#76]
### Context
- svfs version : 0.7.1
- storage provider : OVH
- product : Swift

### Steps to reproduce this issue :

1. Mount a swift storage with svfs (/mnt/backup)
2. Declare it in proxmox as a Directory storage
3. Backup to it a CT or VM
4. See the error in the proxmox panel : 

> 
ERROR: Backup of VM 100 failed - unable to rename '/mnt/backup/dump/vzdump-lxc-100-2016_06_16-17_31_28.tar.dat' to '/mnt/backup/dump/vzdump-lxc-100-2016_06_16-17_31_28.tar.lzo

and in the cli : 

```
 2016/06/16 17:32:14 fuse: panic in handler for Rename [ID=0xcda0 Node=0xa Uid=0 Gid=0 Pid=28539] from "vzdump-lxc-100-2016_06_16-17_31_28.tar.dat" to dirnode 0xa "vzdump-lxc-100-2016_06_16-17_31_28.tar.lzo": runtime error: invalid memory address or nil pointer dereference
 goroutine 62321 [running]:
 github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x7f5bbf5bc9c8, 0xc8272969c0, 0xc827507ec8, 0xc827507de7)
         /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:850 +0xaf
 panic(0x8a1f40, 0xc82000e0b0)
         /home/admin/.gvm/gos/go1.6.2/src/runtime/panic.go:443 +0x4e9
 github.com/ovh/svfs/svfs.(*Object).delete(0xc82730a2a0, 0x0, 0x0)
         /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/svfs/object.go:132 +0xe4
 github.com/ovh/svfs/svfs.(*Object).rename(0xc82730a2a0, 0xc8209b6050, 0xc820ba8300, 0x2a, 0x0, 0x0)
         /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/svfs/object.go:170 +0x96
 github.com/ovh/svfs/svfs.(*Directory).Rename(0xc8209b6050, 0x7f5bbf5b0c78, 0xc8273eb040, 0xc8272969c0, 0x7f5bbf644258, 0xc8209b6050, 0x0, 0x0)
         /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/svfs/directory.go:391 +0x1d1
 github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc8211fe540, 0x7f5bbf5b0c78, 0xc8273eb040, 0x7f5bbf644258, 0xc8209b6050, 0xc8273ea540, 0x7f5bbf5bc9c8, 0xc8272969c0, 0xc827507ec8, 0x0, ...)
         /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:1322 +0x3871
 github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).serve(0xc8211fe540, 0x7f5bbf5bc9c8, 0xc8272969c0)
         /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:871 +0x740
 github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc8211fe540, 0x7f5bbf5bc9c8, 0xc8272969c0)
         /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:418 +0x6d
 created by github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).Serve
         /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:419 +0x580
```

### Results you expected :
The file is correctly renamed with no error during the operation

### Results you observed :
The file *.dat is correctly created/copied into the swift storage, and after that, when proxmox begin to rename it, it fails and show the error as below, and an error appear in the cli and the file is not correctly renamed

### Debug log :

```
2016/06/16 17:48:15 FUSE: -> [ID=0x4b31] Write 17753
2016/06/16 17:48:15 FUSE: <- Write [ID=0x4b32 Node=0x5 Uid=0 Gid=0 Pid=6377] 0x1 4 @280313654 fl=WriteLockOwner lock=16639036429977413056 ffl=OpenWriteOnly
2016/06/16 17:48:15 FUSE: -> [ID=0x4b32] Write 4
2016/06/16 17:48:15 FUSE: <- Flush [ID=0x4b33 Node=0x5 Uid=0 Gid=0 Pid=6377] 0x1 fl=0x0 lk=0xe6e9bb79c59665c0
2016/06/16 17:48:15 FUSE: -> [ID=0x4b33] Flush
2016/06/16 17:48:15 FUSE: <- Release [ID=0x4b34 Node=0x5 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenWriteOnly rfl=0x2 owner=0xaed34d09
2016/06/16 17:48:15 FUSE: <- Lookup [ID=0x4b35 Node=0x4 Uid=0 Gid=0 Pid=6356] "vzdump-lxc-100-2016_06_16-17_47_34.tar.lzo"
2016/06/16 17:48:15 FUSE: -> [ID=0x4b35] Lookup error=ENOENT
2016/06/16 17:48:15 FUSE: <- Rename [ID=0x4b36 Node=0x4 Uid=0 Gid=0 Pid=6356] from "vzdump-lxc-100-2016_06_16-17_47_34.tar.dat" to dirnode 0x4 "vzdump-lxc-100-2016_06_16-17_47_34.tar.lzo"
2016/06/16 17:48:15 fuse: panic in handler for Rename [ID=0x4b36 Node=0x4 Uid=0 Gid=0 Pid=6356] from "vzdump-lxc-100-2016_06_16-17_47_34.tar.dat" to dirnode 0x4 "vzdump-lxc-100-2016_06_16-17_47_34.tar.lzo": runtime error: invalid memory address or nil pointer dereference
goroutine 20418 [running]:
github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x7fc5b4c939c0, 0xc820288960, 0xc820673eb8, 0xc820673dd7)
        /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:850 +0xaf
panic(0x8a1f40, 0xc82000e0b0)
        /home/admin/.gvm/gos/go1.6.2/src/runtime/panic.go:443 +0x4e9
github.com/ovh/svfs/svfs.(*Object).delete(0xc82059e3c0, 0x0, 0x0)
        /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/svfs/object.go:132 +0xe4
github.com/ovh/svfs/svfs.(*Object).rename(0xc82059e3c0, 0xc820389450, 0xc82115c930, 0x2a, 0x0, 0x0)
        /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/svfs/object.go:170 +0x96
github.com/ovh/svfs/svfs.(*Directory).Rename(0xc820389450, 0x7fc5b4c91e10, 0xc827252980, 0xc820288960, 0x7fc5b4c91c60, 0xc820389450, 0x0, 0x0)
        /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/svfs/directory.go:391 +0x1d1
github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc8211b3980, 0x7fc5b4c91e10, 0xc827252980, 0x7fc5b4c91c60, 0xc820389450, 0xc82010b440, 0x7fc5b4c939c0, 0xc820288960, 0xc820673eb8, 0x0, ...)
        /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:1322 +0x3871
github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).serve(0xc8211b3980, 0x7fc5b4c939c0, 0xc820288960)
        /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:871 +0x740
github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc8211b3980, 0x7fc5b4c939c0, 0xc820288960)
        /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:418 +0x6d
created by github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).Serve
        /home/admin/.gvm/pkgsets/go1.6.2/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:419 +0x580
2016/06/16 17:48:15 FUSE: -> [ID=0x4b36] Rename error=EIO: handler panicked: runtime error: invalid memory address or nil pointer dereference
2016/06/16 17:48:15 FUSE: <- Getattr [ID=0x4b37 Node=0x5 Uid=0 Gid=0 Pid=6356] 0x0 fl=0
2016/06/16 17:48:15 FUSE: -> [ID=0x4b37] Getattr valid=1m0s ino=17197592143614561102 size=280313658 mode=-rwx------
2016/06/16 17:48:15 FUSE: <- Remove [ID=0x4b38 Node=0x4 Uid=0 Gid=0 Pid=6356] "vzdump-lxc-100-2016_06_16-17_47_34.tar.dat" dir=false
2016/06/16 17:48:16 FUSE: -> [ID=0x4b34] Release
2016/06/16 17:48:16 FUSE: -> [ID=0x4b38] Remove
2016/06/16 17:48:16 FUSE: <- Forget [ID=0x4b39 Node=0x5 Uid=0 Gid=0 Pid=0] 1
2016/06/16 17:48:16 FUSE: -> [ID=0x4b39] Forget
2016/06/16 17:48:16 FUSE: <- Getattr [ID=0x4b3a Node=0x4 Uid=0 Gid=0 Pid=6814] 0x0 fl=0
2016/06/16 17:48:16 FUSE: -> [ID=0x4b3a] Getattr valid=1m0s ino=9250735732976992002 size=4096 mode=drwx------
2016/06/16 17:48:16 FUSE: <- Lookup [ID=0x4b3b Node=0x4 Uid=0 Gid=0 Pid=6814] "vzdump-lxc-100-2016_06_16-17_47_34.log"
2016/06/16 17:48:16 FUSE: -> [ID=0x4b3b] Lookup error=ENOENT
2016/06/16 17:48:16 FUSE: <- Lookup [ID=0x4b3c Node=0x4 Uid=0 Gid=0 Pid=6814] "vzdump-lxc-100-2016_06_16-17_47_34.log"
2016/06/16 17:48:16 FUSE: -> [ID=0x4b3c] Lookup error=ENOENT
2016/06/16 17:48:16 FUSE: <- Lookup [ID=0x4b3d Node=0x4 Uid=0 Gid=0 Pid=6814] "vzdump-lxc-100-2016_06_16-17_47_34.log"
2016/06/16 17:48:16 FUSE: -> [ID=0x4b3d] Lookup error=ENOENT
2016/06/16 17:48:16 FUSE: <- Create [ID=0x4b3e Node=0x4 Uid=0 Gid=0 Pid=6814] "vzdump-lxc-100-2016_06_16-17_47_34.log" fl=OpenWriteOnly+OpenCreate+OpenExclusive mode=-rw-r--r-- umask=-----w--w-
2016/06/16 17:48:17 FUSE: -> [ID=0x4b3e] Create {0x5 gen=8 valid=1m0s attr={valid=1m0s ino=15444723865986717400 size=0 mode=-rwx------}} {0x1 fl=OpenDirectIO+OpenNonSeekable}
2016/06/16 17:48:17 FUSE: <- Write [ID=0x4b3f Node=0x5 Uid=0 Gid=0 Pid=6814] 0x1 643 @0 fl=WriteLockOwner lock=13349314869124715126 ffl=OpenWriteOnly
2016/06/16 17:48:17 FUSE: -> [ID=0x4b3f] Write 643
2016/06/16 17:48:17 FUSE: <- Flush [ID=0x4b40 Node=0x5 Uid=0 Gid=0 Pid=6814] 0x1 fl=0x0 lk=0xb9424b255104d276
2016/06/16 17:48:17 FUSE: -> [ID=0x4b40] Flush
2016/06/16 17:48:17 FUSE: <- Release [ID=0x4b41 Node=0x5 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenWriteOnly rfl=0x2 owner=0xcba0c4bf
2016/06/16 17:48:17 FUSE: -> [ID=0x4b41] Release
2016/06/16 17:48:23 FUSE: <- Lookup [ID=0x4b42 Node=0x1 Uid=0 Gid=0 Pid=4319] "dump"
2016/06/16 17:48:23 FUSE: -> [ID=0x4b42] Lookup 0x6 gen=8 valid=1m0s attr={valid=1m0s ino=9250735732976992002 size=4096 mode=drwx------}
2016/06/16 17:48:23 FUSE: <- Lookup [ID=0x4b44 Node=0x1 Uid=0 Gid=0 Pid=4319] "dump"
2016/06/16 17:48:23 FUSE: <- Forget [ID=0x4b43 Node=0x6 Uid=0 Gid=0 Pid=0] 1
2016/06/16 17:48:23 FUSE: -> [ID=0x4b43] Forget
2016/06/16 17:48:23 FUSE: -> [ID=0x4b44] Lookup 0x6 gen=8 valid=1m0s attr={valid=1m0s ino=9250735732976992002 size=4096 mode=drwx------}
2016/06/16 17:48:23 FUSE: <- Forget [ID=0x4b45 Node=0x5 Uid=0 Gid=0 Pid=0] 1
2016/06/16 17:48:23 FUSE: -> [ID=0x4b45] Forget
2016/06/16 17:48:23 FUSE: <- Forget [ID=0x4b46 Node=0x2 Uid=0 Gid=0 Pid=0] 1
2016/06/16 17:48:23 FUSE: -> [ID=0x4b46] Forget
2016/06/16 17:48:23 FUSE: <- Statfs [ID=0x4b47 Node=0x1 Uid=0 Gid=0 Pid=6872]
2016/06/16 17:48:23 FUSE: <- Forget [ID=0x4b48 Node=0x3 Uid=0 Gid=0 Pid=0] 1
2016/06/16 17:48:23 FUSE: -> [ID=0x4b48] Forget
2016/06/16 17:48:23 FUSE: <- Forget [ID=0x4b49 Node=0x4 Uid=0 Gid=0 Pid=0] 1
2016/06/16 17:48:23 FUSE: -> [ID=0x4b49] Forget
2016/06/16 17:48:24 FUSE: -> [ID=0x4b47] Statfs blocks=2251799813682339/2251799813682339/2251799813685247 files=0/5 bsize=4096 frsize=0 namelen=0
2016/06/16 17:48:33 FUSE: <- Statfs [ID=0x4b4a Node=0x1 Uid=0 Gid=0 Pid=6972]
2016/06/16 17:48:33 FUSE: -> [ID=0x4b4a] Statfs blocks=2251799813682339/2251799813682339/2251799813685247 files=0/5 bsize=4096 frsize=0 namelen=0
2016/06/16 17:48:43 FUSE: <- Statfs [ID=0x4b4b Node=0x1 Uid=0 Gid=0 Pid=7073]
2016/06/16 17:48:43 FUSE: -> [ID=0x4b4b] Statfs blocks=2251799813682339/2251799813682339/2251799813685247 files=0/5 bsize=4096 frsize=0 namelen=0
2016/06/16 17:48:53 FUSE: <- Statfs [ID=0x4b4c Node=0x1 Uid=0 Gid=0 Pid=7174]
2016/06/16 17:48:53 FUSE: -> [ID=0x4b4c] Statfs blocks=2251799813682339/2251799813682339/2251799813685247 files=0/5 bsize=4096 frsize=0 namelen=0
```

### Additional information :

![capture](https://cloud.githubusercontent.com/assets/9059362/16123501/8385b968-33eb-11e6-8765-55609541336d.PNG)

**Comment by maxs97** [comment]
I can confirm that. Worked with 0.6.3, after that I was not able to upload backups to swift.

**Comment by ele0s** [comment]
Yep, I've just tested, and indeed, it works in 6.3 with the last version of Proxmox
So I'll downgrade svfs until a fix will be committed, Thanks @maxs97 <3
